{% set name = "pandas-summary" %}
{% set version = "0.2.0" %}
{% set sha256 = "dadad65e2e56ac37ea2d16049966d9f36f745a568783b2ce7568595eef001ccf" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - pandas_summary

  requires:
    - pytest

about:
  home: https://github.com/mouradmourafiq/pandas-summary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extension to pandas describe function.
  dev_url: https://github.com/mouradmourafiq/pandas-summary

extra:
  recipe-maintainers:
    - proinsias
