{% set name = "pandas-summary" %}
{% set version = "0.1.0" %}
{% set sha256 = "91db5092518a0a74fedd05e95a2110217aa9e9476ba99811219aa14e5cd2b102" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - numpy
    - pandas

test:
  imports:
    - pandas_summary

  requires:
    - pytest

about:
  home: https://github.com/mouradmourafiq/pandas-summary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extension to pandas describe function.
  dev_url: https://github.com/mouradmourafiq/pandas-summary

extra:
  recipe-maintainers:
    - proinsias
