travis:
  secure:
    BINSTAR_TOKEN: J3a2W8pYeCoR2+IS19x+EEFoFE1XfaZovCiknqagyEcAMGTuwuPjYoOYL3lKVP9vW6pxTsUDw5GeHozhN4s4iTpBo/S6JDoncC3BFcoyZ8cQQfXnpAsNehpj9oPO90CEdIiuaWhYn/kJDv0d+eljxx79eO5wWykmKQ+3Natf0Fb3MqsFOIp2oFL6vaoqdRafqw/47cnbw1ZxrePyOYpX4WNnEE5tipXtlYycdTrItXb9CDGaoHKxuBqzUPeg7h5kNSXSgsgAxHOHZn/dPnrXM86BNC5CZSvjO2vHm9or899PFRMSWZw6UeUGDe2lO8K7uvVceiOAu5rq9dQP2QQTH1k0w0O+3R4jKirH1XJenJW34bnphY9AGwkzDlotAKLBE6d8fd+P3rTLpc5terPKJO3WhCXpgaxNUJYoIy/ckXnc0qBUuyGet9E0tVf4TAlHrpnvhkDjLKVMTp0Pe2GG3svqwz9K3aW7Rqlxl2hAJyuWX/n55xKqJJm4j/jdft7DUbIoiigNj3MgRj0FwviYNV4bCLfVGYeP7hVj6fCPyoaK7rAWorWqZlc0KKrcwVzAmdc9m2x1S2rPByz+hcrnAhmRTKkKYc/66Nk5NnGll6CflfBKtKV3i3QzZvkpb98HXIpmEYEnp+yAAcX8cmgqyIQVx1QcTc+9aNPTnq1EIGU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
